package:
  name: menpobench
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pathlib 1.0  # [py2k]
    - menpofit 0.2.*
    - pyyaml 3.*


test:

  requires:
    - nose
    - nose-exclude

  imports:
    - menpobench

about:
  home: https://github.com/menpo/menpobench/
  license: BSD License
