package:
  name: menpobench
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpofit 0.2.*

test:

  requires:
    - nose
    - nose-exclude

  imports:
    - menpobench

about:
  home: https://github.com/menpo/menpobench/
  license: BSD License
